use_frameworks!

source 'https://github.com/media-net/mnet-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MNAdSdk_Example' do
  # This is equivalent to 'MNAdSdk/Base'
  pod 'MNetAdSdk', :path => '../MNetAdSdk.podspec.json'
  pod 'mopub-ios-sdk', '~> 4.12.0'
  pod 'MBProgressHUD'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
  pod 'Toast', '~> 3.1.0'

target 'MNAdSdk_Tests' do
    inherit! :search_paths
    pod 'Nocilla'
end

end
